config/routes.rb
Bcmets::Application.routes.draw do
  get 'timeline/index'

  resources :feeds
  resources :links
  resources :donations do
      collection do
    get :stats
    end
  end

  namespace "api" do
    post "import_emails"
    post "import_feeds"
    post "index_articles"
  end

  get 'login' => 'user_sessions#new', as: :login
  post 'login' => 'user_sessions#create'
  match 'logout' => 'user_sessions#destroy', as: :logout, via: [:get, :post]
  match '/register/:activation_code' => 'activations#new', as: :register, via: [:get, :post]
  match '/activate/:id' => 'activations#create', as: :activate, via: [:get, :post]
  match '/password_reset/:activation_code' => 'activations#reset_password', as: :reset_password, via: [:get, :post]
  match '/user_profile/:id' => 'users#profile', as: :user_profile, via: [:get, :post]
  match '/users/password' => 'users#password', as: :forgot_password, via: [:get, :post]
  match '/users/edit_email' => 'users#edit_email', as: :edit_email, via: [:get, :post]
  match '/users/edit_email' => 'users#edit_email', as: :save_email, via: [:get, :post]
  match '/users/edit_password' => 'users#edit_password', as: :edit_password, via: [:get, :post]
  match '/users/edit_password' => 'users#edit_password', as: :save_password, via: [:get, :post]
  match '/users/unsubscribe' => 'users#unsubscribe', as: :unsubscribe, via: [:get, :post]
  resources :user_sessions
  resources :users
  resources :articles
  match 'donations.html' => 'pages#donate', via: [:get, :post]
  match 'saved' => 'articles#saved', via: [:get, :post]
  match '/archive/:year/:month/date' => 'archive#month_by_date', as: :archive_month_by_date, year: /\d{4}/, via: [:get, :post]
  get 'archive/author' => 'archive#author', as: :author_search
  match '/article/:id/reply/' => 'articles#reply', as: :article_reply, via: [:get, :post]
  match '/articles/:id/set_saved' => 'articles#set_saved', as: :article_set_saved, via: [:get, :post]
  match '/articles/:id/is_saved' => 'articles#is_saved', as: :article_is_saved, via: [:get, :post]
  get 'archive/:year/:month' => 'archive#month', as: :archive_month, year: /\d{4}/
  get 'post.pl' => 'articles#new'
  get 'post' => 'articles#new', as: :post
  get 'donate' => 'pages#donate'
  get 'blogs' => 'feed_entries#index', as: :feed_entries
  get '/' => 'archive#index', as: :root
  match '/:controller(/:action(/:id))', via: [:get, :post]
end

app/models/feed.rb
require 'open-uri'
require 'nokogiri'

class Feed < ActiveRecord::Base
  has_many :entries, class_name: "FeedEntry"

  def last_n_entries(n)
    entries.order("created_at DESC").limit(n)
  end

  def last_entry_date
    entries.order("created_at DESC").first.created_at
  end

  def has_entry?(guid: nil)
    entries.map(&:guid).include?(guid)
  end

  def add_entry(entry)
    entries << entry unless has_entry?(guid: entry.guid)
  end
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  before_filter :require_admin

  def index
    @feeds = Feed.all
  end

  def show
    @feed = Feed.find(params[:id])
    @feed_entries = @feed ? @feed.last_n_entries(5) : []
  end

  def new
    @feed = Feed.new
  end

  def create
    @feed = Feed.new(params[:feed])
    if @feed.save
      flash[:notice] = "Successfully created feed."
      redirect_to @feed
    else
      render action: 'new'
    end
  end

  def edit
    @feed = Feed.find(params[:id])
  end

  def update
    @feed = Feed.find(params[:id])
    if @feed.update_attributes(params[:feed])
      flash[:notice] = "Successfully updated feed."
      redirect_to @feed
    else
      render action: 'edit'
    end
  end

  def destroy
    @feed = Feed.find(params[:id])
    @feed.destroy
    flash[:notice] = "Successfully destroyed feed."
    redirect_to feeds_url
  end
end

app/views/feeds/_form.html.erb
<%= form_for @feed do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </p>
  <p><%= f.submit "Submit" %></p>
<% end %>

app/views/feeds/edit.html.erb
<%= title "Edit Feed" %>

<%= render :partial => 'form' %>

<p>
  <%= link_to "Show", @feed %> |
  <%= link_to "View All", feeds_path %>
</p>

app/views/feeds/index.html.erb
<% wide_page! %>
<% title "Feeds" %>

<table>
  <tr>
    <th>Url</th>
    <th>Last Entry</th>
  </tr>
  <% for feed in @feeds %>
    <tr>
      <td style="overflow-x: hidden; max-width: 300px; padding-right: 20px;"><%=h feed.url %></td>
      <td><%= time_ago_in_words(feed.last_entry_date) %> ago</td>
      <td><%= link_to "Show", feed %></td>
      <td><%= link_to "Edit", edit_feed_path(feed) %></td>
      <td><%= link_to "Destroy", feed, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Feed", new_feed_path %></p>

app/views/feeds/new.html.erb
<% title "New Feed" %>

<%= render :partial => 'form' %>

<p><%= link_to "Back to List", feeds_path %></p>

app/views/feeds/show.html.haml
- title "Feed"

%p
  %strong URL:
  =h @feed.url

- if @feed_entries.any?
  %h2 Recent Entries
  %ul
    - @feed_entries.each do |entry|
      %li
        = link_to entry.name, entry.url
        = "(#{time_ago_in_words(entry.created_at)} ago)"

%p
  = link_to "Edit", edit_feed_path(@feed)
  |
  = link_to "Destroy", @feed, :confirm => 'Are you sure?', :method => :delete
  |
  = link_to "View All", feeds_path