config/routes.rb
Bcmets::Application.routes.draw do
  get 'timeline/index'

  resources :feeds
  resources :links
  resources :donations do
      collection do
    get :stats
    end
  end

  namespace "api" do
    post "import_emails"
    post "import_feeds"
    post "index_articles"
  end

  get 'login' => 'user_sessions#new', as: :login
  post 'login' => 'user_sessions#create'
  match 'logout' => 'user_sessions#destroy', as: :logout, via: [:get, :post]
  match '/register/:activation_code' => 'activations#new', as: :register, via: [:get, :post]
  match '/activate/:id' => 'activations#create', as: :activate, via: [:get, :post]
  match '/password_reset/:activation_code' => 'activations#reset_password', as: :reset_password, via: [:get, :post]
  match '/user_profile/:id' => 'users#profile', as: :user_profile, via: [:get, :post]
  match '/users/password' => 'users#password', as: :forgot_password, via: [:get, :post]
  match '/users/edit_email' => 'users#edit_email', as: :edit_email, via: [:get, :post]
  match '/users/edit_email' => 'users#edit_email', as: :save_email, via: [:get, :post]
  match '/users/edit_password' => 'users#edit_password', as: :edit_password, via: [:get, :post]
  match '/users/edit_password' => 'users#edit_password', as: :save_password, via: [:get, :post]
  match '/users/unsubscribe' => 'users#unsubscribe', as: :unsubscribe, via: [:get, :post]
  resources :user_sessions
  resources :users
  resources :articles
  match 'donations.html' => 'pages#donate', via: [:get, :post]
  match 'saved' => 'articles#saved', via: [:get, :post]
  match '/archive/:year/:month/date' => 'archive#month_by_date', as: :archive_month_by_date, year: /\d{4}/, via: [:get, :post]
  get 'archive/author' => 'archive#author', as: :author_search
  match '/article/:id/reply/' => 'articles#reply', as: :article_reply, via: [:get, :post]
  match '/articles/:id/set_saved' => 'articles#set_saved', as: :article_set_saved, via: [:get, :post]
  match '/articles/:id/is_saved' => 'articles#is_saved', as: :article_is_saved, via: [:get, :post]
  get 'archive/:year/:month' => 'archive#month', as: :archive_month, year: /\d{4}/
  get 'post.pl' => 'articles#new'
  get 'post' => 'articles#new', as: :post
  get 'donate' => 'pages#donate'
  get 'blogs' => 'feed_entries#index', as: :feed_entries
  get '/' => 'archive#index', as: :root
  match '/:controller(/:action(/:id))', via: [:get, :post]
end

app/views/admin/index.html.haml
- wide_page!
%h1 Administration Interface
%ul
  %li
    = link_to "Import from Mailman", :action => 'mailman_import'
  %li
    = link_to "List users", users_path
  %li
    = link_to "Links", links_path
  %li
    = link_to "Feeds", feeds_path
  %li
    = link_to "Donation", donations_path

app/views/admin/mailman_import.html.haml
%h2 Import Users from Mailman

- form_tag do
  %p
    File path: 
    = text_field :file, :name
    = submit_tag "Import"
  %p Reminder: use <tt>cd /home/mailman; bin/dumpdb lists/bcmets/config.pck > file</tt>

app/views/admin/users.html.haml
%h2 Users

= link_to("Add User", new_user_path)

%table#users.admin
  %thead
    %tr
      %th User
      %th Joined
      %th Delivery
  %tbody
    - for user in @users do
      %tr{:class => cycle('admin-odd', 'admin-even')}
        %td=h "#{user.name} <#{user.email}>"
        %td= user.created_at.to_date.to_s(:db)
        %td= user.email_delivery
        %td
          = link_to 'V', :controller => user_profile_path(user)
          = link_to 'E', edit_user_path(user)