config/routes.rb
Bcmets::Application.routes.draw do
  get 'timeline/index'

  resources :feeds
  resources :links
  resources :donations do
      collection do
    get :stats
    end
  end

  namespace "api" do
    post "import_emails"
    post "import_feeds"
    post "index_articles"
  end

  get 'login' => 'user_sessions#new', as: :login
  post 'login' => 'user_sessions#create'
  match 'logout' => 'user_sessions#destroy', as: :logout, via: [:get, :post]
  match '/register/:activation_code' => 'activations#new', as: :register, via: [:get, :post]
  match '/activate/:id' => 'activations#create', as: :activate, via: [:get, :post]
  match '/password_reset/:activation_code' => 'activations#reset_password', as: :reset_password, via: [:get, :post]
  match '/user_profile/:id' => 'users#profile', as: :user_profile, via: [:get, :post]
  match '/users/password' => 'users#password', as: :forgot_password, via: [:get, :post]
  match '/users/edit_email' => 'users#edit_email', as: :edit_email, via: [:get, :post]
  match '/users/edit_email' => 'users#edit_email', as: :save_email, via: [:get, :post]
  match '/users/edit_password' => 'users#edit_password', as: :edit_password, via: [:get, :post]
  match '/users/edit_password' => 'users#edit_password', as: :save_password, via: [:get, :post]
  match '/users/unsubscribe' => 'users#unsubscribe', as: :unsubscribe, via: [:get, :post]
  resources :user_sessions
  resources :users
  resources :articles
  match 'donations.html' => 'pages#donate', via: [:get, :post]
  match 'saved' => 'articles#saved', via: [:get, :post]
  match '/archive/:year/:month/date' => 'archive#month_by_date', as: :archive_month_by_date, year: /\d{4}/, via: [:get, :post]
  get 'archive/author' => 'archive#author', as: :author_search
  match '/article/:id/reply/' => 'articles#reply', as: :article_reply, via: [:get, :post]
  match '/articles/:id/set_saved' => 'articles#set_saved', as: :article_set_saved, via: [:get, :post]
  match '/articles/:id/is_saved' => 'articles#is_saved', as: :article_is_saved, via: [:get, :post]
  get 'archive/:year/:month' => 'archive#month', as: :archive_month, year: /\d{4}/
  get 'post.pl' => 'articles#new'
  get 'post' => 'articles#new', as: :post
  get 'donate' => 'pages#donate'
  get 'blogs' => 'feed_entries#index', as: :feed_entries
  get '/' => 'archive#index', as: :root
  match '/:controller(/:action(/:id))', via: [:get, :post]
end

app/models/donation.rb
class Donation < ActiveRecord::Base
  validates_presence_of :amount
  validates_presence_of :email
  validates_presence_of :date
  validates_numericality_of :amount

  def self.total_this_month(date = Time.zone.today)
    start_of_month = Date.new(date.year, date.month, 1)
    end_of_month = 1.month.since(start_of_month)
    where(date: (start_of_month...end_of_month)).sum(:amount)
  end

  def self.total_this_year(date = Time.zone.today)
    start_of_year = Date.new(date.year, 1, 1)
    end_of_year = 1.year.since(start_of_year)
    where(date: (start_of_year...end_of_year)).sum(:amount)
  end

  def self.last_donation_on
    maximum(:date)
  end
end

app/controllers/donations_controller.rb
class DonationsController < ApplicationController
  before_filter :require_admin, except: :stats

  def index
    @donations = Donation.order('date DESC')
    @donation = Donation.new
  end

  def show
    @donation = Donation.find(params[:id])
  end

  def new
    @donation = Donation.new
  end

  def create
    @donation = Donation.new(donation_params)
    if @donation.save
      flash[:notice] = "Successfully created donation."
      redirect_to donations_path
    else
      render action: 'new'
    end
  end

  def edit
    @donation = Donation.find(params[:id])
  end

  def update
    @donation = Donation.find(params[:id])
    if @donation.update_attributes(donation_params)
      flash[:notice] = "Successfully updated donation."
      redirect_to @donations
    else
      render action: 'edit'
    end
  end

  def destroy
    @donation = Donation.find(params[:id])
    @donation.destroy
    flash[:notice] = "Successfully destroyed donation."
    redirect_to donations_url
  end

  def stats
    render text: "#{Donation.total_this_month} #{Donation.total_this_year}"
  end

  private

  def donation_params
    params.require(:donation).permit(:amount, :email, :date)
  end
end

app/views/donations/_form.html.erb
<%= form_for @donation do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :amount %><br />
    <%= f.text_field :amount %>
  </p>
  <p>
    <%= f.label :date %><br />
    <%= f.date_select :date %>
  </p>
  <p><%= f.submit "Submit" %></p>
<% end %>

app/views/donations/edit.html.erb
<% title "Edit Donation" %>

<%= render :partial => 'form' %>

<p>
  <%= link_to "Show", @donation %> |
  <%= link_to "View All", donations_path %>
</p>

app/views/donations/index.html.erb
<% title "Donations" %>

<p><%= link_to "New Donation", "javascript:;", :id => "new_donation_link" %></p>

<div id="new_donation_form">
  <%= render :partial => "form" %>
</div>

<table>
  <tr>
    <th>Email</th>
    <th>Amount</th>
    <th>Date</th>
  </tr>
  <% for donation in @donations %>
    <tr>
      <td><%=h donation.email %></td>
      <td><%=h donation.amount %></td>
      <td><%=h donation.date %></td>
      <td><%= link_to "Edit", edit_donation_path(donation) %></td>
      <td><%= link_to "Destroy", donation, :data => { :confirm => 'Are you sure?' }, :method => :delete %></td>
    </tr>
  <% end %>
</table>

<script type="text/javascript">
  $(function() {
    $('#new_donation_link').click(function() {
      $('#new_donation_form').toggle("slow");
    });
  });
</script>

app/views/donations/new.html.erb
<% title "New Donation" %>

<%= render :partial => 'form' %>

<p><%= link_to "Back to List", donations_path %></p>

app/views/donations/show.html.erb
<% title "Donation" %>

<p>
  <strong>Email:</strong>
  <%=h @donation.email %>
</p>
<p>
  <strong>Amount:</strong>
  <%=h @donation.amount %>
</p>
<p>
  <strong>Date:</strong>
  <%=h @donation.date %>
</p>

<p>
  <%= link_to "Edit", edit_donation_path(@donation) %> |
  <%= link_to "Destroy", @donation, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", donations_path %>
</p>