config/routes.rb
Bcmets::Application.routes.draw do
  get 'timeline/index'

  resources :feeds
  resources :links
  resources :donations do
      collection do
    get :stats
    end
  end

  namespace "api" do
    post "import_emails"
    post "import_feeds"
    post "index_articles"
  end

  get 'login' => 'user_sessions#new', as: :login
  post 'login' => 'user_sessions#create'
  match 'logout' => 'user_sessions#destroy', as: :logout, via: [:get, :post]
  match '/register/:activation_code' => 'activations#new', as: :register, via: [:get, :post]
  match '/activate/:id' => 'activations#create', as: :activate, via: [:get, :post]
  match '/password_reset/:activation_code' => 'activations#reset_password', as: :reset_password, via: [:get, :post]
  match '/user_profile/:id' => 'users#profile', as: :user_profile, via: [:get, :post]
  match '/users/password' => 'users#password', as: :forgot_password, via: [:get, :post]
  match '/users/edit_email' => 'users#edit_email', as: :edit_email, via: [:get, :post]
  match '/users/edit_email' => 'users#edit_email', as: :save_email, via: [:get, :post]
  match '/users/edit_password' => 'users#edit_password', as: :edit_password, via: [:get, :post]
  match '/users/edit_password' => 'users#edit_password', as: :save_password, via: [:get, :post]
  match '/users/unsubscribe' => 'users#unsubscribe', as: :unsubscribe, via: [:get, :post]
  resources :user_sessions
  resources :users
  resources :articles
  match 'donations.html' => 'pages#donate', via: [:get, :post]
  match 'saved' => 'articles#saved', via: [:get, :post]
  match '/archive/:year/:month/date' => 'archive#month_by_date', as: :archive_month_by_date, year: /\d{4}/, via: [:get, :post]
  get 'archive/author' => 'archive#author', as: :author_search
  match '/article/:id/reply/' => 'articles#reply', as: :article_reply, via: [:get, :post]
  match '/articles/:id/set_saved' => 'articles#set_saved', as: :article_set_saved, via: [:get, :post]
  match '/articles/:id/is_saved' => 'articles#is_saved', as: :article_is_saved, via: [:get, :post]
  get 'archive/:year/:month' => 'archive#month', as: :archive_month, year: /\d{4}/
  get 'post.pl' => 'articles#new'
  get 'post' => 'articles#new', as: :post
  get 'donate' => 'pages#donate'
  get 'blogs' => 'feed_entries#index', as: :feed_entries
  get '/' => 'archive#index', as: :root
  match '/:controller(/:action(/:id))', via: [:get, :post]
end

app/models/archive.rb
class Archive
  def self.in_range(year, month)
    this_year = Date.today.year
    (2000..this_year).include?(year.to_i) && (1..12).include?(month.to_i)
  end
end

app/controllers/archive_controller.rb
require 'will_paginate/array'

class ArchiveController < ApplicationController
  before_filter :enable_search_engines, only: :index

  def index
    now = Time.zone.now
    @year = now.year
    @month = now.month
  end

  def month
    @year, @month = params[:year], params[:month]
    month_year = "#{Date::MONTHNAMES[@month.to_i]} #{@year}"
    @title = month_year

    if !Archive.in_range(@year, @month)
      flash[:notice] = "No articles for #{@month}/#{@year}"
      return redirect_to root_url
    end

    candidates = Article.for_month(@year.to_i, @month.to_i)
    @articles = Article.thread_tree(candidates).reverse
    @article_count = candidates.count

    expires_in 2.minutes
  end

  def month_by_date
    @year, @month = params[:year], params[:month]
    @title = "#{Date::MONTHNAMES[@month.to_i]} #{@year}"

    candidates = Article.for_month(@year.to_i, @month.to_i, "received_at DESC")
    @articles = candidates.group_by { |article| article.received_at.to_date }
    @dates = @articles.keys.sort { |a, b| b <=> a }
    @article_count = candidates.count
  end

  def article
    @article = Article.find_by_id(params[:id])
    redirect_to @article
  end

  # For people with legacy bookmarks - can probably remove this feature after Dec 2010.
  def old_article
    year, month = old_year_month
    article_number = params[:article_number]
    @article = Article.find_by_legacy_id("#{year}-#{month}/#{article_number}")
    if @article.nil?
      flash[:notice] = "Oops.  We couldn't find your bookmark.  " \
          'You can use the Search function to try and locate it, or click on a month below.'
      redirect_to action: "index"
    else
      redirect_to action: "article", id: @article
    end
  end

  def search
    @search = SearchOptions.new(params).run
    @title = @search.query
    if @search.error
      flash[:notice] = @search.error.html_safe
    end
  end

  def author
    @email = params[:email]
    @articles = Article.where(email: params[:email]).order("sent_at DESC")
    unless params[:page] == "all"
      @articles = @articles.paginate(page: params[:page])
      @pagination = true
    end
  end

  def this_month
    date = Time.zone.today
    redirect_to url_for(action: 'month', year: date.year, month: date.month)
  end

  private

  def send_via_email(article)
    article.send_via_email
  end

  def enable_search_engines
    @indexable = true
  end

  def old_year_month
    params[:old_year_month] =~ /(\d{4})-(\d{2})/ && [$1, $2]
  end
end

app/helpers/archive_helper.rb
module ArchiveHelper
  def month_link(year, month)
    text = "#{Date::MONTHNAMES[month]} #{year}"

    if year == @year && month == @month
      text = "<strong>#{text}</strong>"
    end

    if (year == @year && month > @month) || (year == 2000 && month == 1)
      return text
    end

    link_to text.html_safe, archive_month_path(year, month)
  end

  def from_linked(author)
    if author.name == author.email
      from = email_linked(author)
    else
      from = author.name + " &lt;" + email_linked(author) + "&gt;"
    end
    from.html_safe
  end

  def email_linked(author)
    %(<a href="/archive/author?email=#{URI.escape author.email}">#{h author.email}</a>)
  end

  def wrap(tag, content)
    "<#{tag}>#{content}</#{tag}>"
  end

  def to_html(text)
    ArticleBodyFormatter.new.format(text)
  end

  def thread_as_html(articles, out = "")
    articles.each do |article|
      out << "<li>"
      out << link_to_article(article) << " "
      out << "<small>#{from_linked(article)}, #{article.sent_at_human}</small>"
      children = article.children
      if !children.nil? && !children.empty?
        out << "<ul>"
        thread_as_html(children, out)
        out << "</ul>"
      end
      out << "</li>"
    end
    out
  end

  def donations(collected, message)
    "#{number_to_currency(collected, precision: 0)} this #{message}"
  end

  def donations_this_month
    donations Donation.total_this_month, "month (target: $500)"
  end

  def donations_this_year
    donations Donation.total_this_year, "year (target: $6,000)"
  end

  def last_donation
    date = Donation.last_donation_on
    if date.nil?
      last_donation = "never"
    elsif date.to_date == Time.zone.today
      last_donation = "today"
    else
      last_donation = "#{time_ago_in_words(date)} ago"
    end
    "Last donation: #{last_donation}"
  end

  def link_to_author(article)
    path = {
      controller: "archive",
      action: "author",
      email: article.email
    }
    link_to h(article.from), path
  end

  def link_to_article(article)
    link = %(<a href="/articles/#{article.id}" class="subject">#{h article.subject}</a>)
    if article.saved_by?(current_user)
      link = %(<span class="star selected"></span>) + link
    end

    link.html_safe
  end
end

app/views/archive/article.html.haml
- if @article.recent?
  = link_to "Reply to this message", article_reply_path(@article), :id => "reply"
#header
  %ul
    %li#from
      From:
      = from_linked(@article)
    %li#date
      Date:
      = @article.sent_at.strftime("%B %d, %Y, %H:%M:%S")
      = "(#{time_ago_in_words(@article.sent_at)} ago)"
#body
  = to_html @article.body
  - if @conversation_roots
    %div.thread
      %h2 Articles in this thread
      %ul.conversation
        = thread_as_html(@conversation_roots)

app/views/archive/author.html.haml
%h1
  = @email
- if @pagination
  %p
    Showing articles
    = @articles.offset + 1
    to
    = @articles.offset + @articles.per_page
    out of
    = @articles.total_entries
    \-
    = link_to("Show All", params.merge(:page => "all"))
  = will_paginate(@articles)
- else
  %p.article_count
    = @articles.size
    articles

%ul.bydate
  - @articles.each do |article|
    %li
      = link_to_article(article).html_safe
      %small
        = article.sent_at_human

- if @pagination
  = will_paginate(@articles)

app/views/archive/index.html.haml
%h1 Archives
%p
  = link_to "Post a message to the list", post_path
.pinned
  %h4 Hi there! Can you help?

  %p
    We are asking you to participate in a research study to find
    out what women with metastatic breast cancer want to know about
    your disease, how you get this information, and what you think
    about the information you have gotten.

  %p
    The link to the Consent Form and survey questionnaire is:
    = link_to "https://www.surveymonkey.com/r/Z5DS6TT", "https://www.surveymonkey.com/r/Z5DS6TT"

  %p
    Thanks for your help.
    %br
    Carol Tucker
    %br
    M. Pilar Martin
    %br
    Ray Jones

- @year.downto(2000).each do |year|
  .year{class: year == @year ? "current" : "old"}
    %h2
      = year
    %ul.index
      - (1..12).each do |month|
        %li
          = month_link(year, month)

app/views/archive/month.html.haml
%h1= @title
- if !@articles.blank?
  %p
    = @article_count
    articles.
    = link_to 'View in date order', archive_month_by_date_path(:year => @year, :month => @month), :class => "date_order"
  %ul.month
    = thread_as_html(@articles).html_safe
- else
  %p
    There are no articles.

app/views/archive/month_by_date.html.haml
- if !@dates.blank?
  %p
    = @article_count
    articles.
    = link_to 'View in thread order', archive_month_path(:year => @year, :month => @month)
  - for date in @dates
    %h2
      = date.strftime("%a %b #{date.day.ordinalize}")
    %ul.bydate
      - for article in @articles[date]
        %li
          = link_to_article(article)
          %small
            = link_to_author(article)
            ,
            = article.received_at.to_s(:short)
- else
%p
  No articles.

app/views/archive/post.html.haml
%h1
  Post a Message
- form_for :article, :url => { :action => "post" }, :html => { :id => "post_form" } do |f|
  %fieldset
    = f.error_messages
    %div
      = f.label :name, "Name"
      %br
      = f.text_field :name
    %div
      = f.label :email, "Email"
      %br
      = f.text_field :email
    - if @article.reply?
      %div
        = f.hidden_field :to
        = f.hidden_field :parent_id
        = f.hidden_field :parent_msgid
        = f.label :reply_type, "Reply To:"
        %br
        = f.select :reply_type, [['List only', 'list'], ['Sender only', 'sender'], ['Both', 'both']]
    %div
      = f.label :subject, "Subject"
      %br
      = f.text_field :subject
    %div{:style => "display:none;"}
      = f.label :body, "Message:"
      %br
      = f.text_area :body, :rows => 30, :cols => 60
    %div
      = f.label :qt, "Message:"
      %br
      = f.text_area :qt, :rows => 30, :cols => 60
    %div
      = submit_tag "Post", :disable_with=>"Sending..."

app/views/archive/search.html.haml
%h2
  Search results for
  = @search.query
%p.sortby
  Sorted by
  = "#{@search.sorting_by}."
  = link_to("Sort by #{@search.switch_sort}", @search.switch_url)
%p.resultcount
  Showing
  = @search.articles_count
  out of
  = pluralize(@search.total_count, "result")

= will_paginate @search.articles
%ul.search_results
  - for article in @search.articles
    %li
      = link_to_article(article)
      %small
        = link_to_author(article)
        ,
        = article.received_at.to_date.strftime("%b %d %Y")
= will_paginate @search.articles